### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by WilliamKelley** [prenda-school/prenda-spark#101]
Noticed these changes in the [Button Figma page](https://www.figma.com/file/y6Ca8BdJtQEd3Of1saRieF/Spark-Design-System-Web?node-id=29%3A0)

Variants (appearance): `solid`, `outlined`, `flat` -> `primary`, `secondary`, `ghost`

Default size: `medium` -> `large`

New 'Active' spec

New 'Loading' spec

@ssbittle Any other changes you know of?

**Comment by ssbittle** [comment]
@WilliamKelley Active state
<img width="134" alt="CleanShot 2021-06-30 at 08 30 44@2x" src="https://user-images.githubusercontent.com/83429562/123969074-790d8280-d97d-11eb-8a04-c9c4a05bc720.png">

**Comment by WilliamKelley** [comment]
@ssbittle I'd like to propose a change to the `variant` names. I know they've already undergone a change, but I think `primary` and `secondary` are less intuitive values for these stylings, at least in a dev's eyes.

Mui's default variants are `contained`, `outlined`, and `text`. They reserve `primary` and `secondary` to describe the _color_ options that can be combined with any variant. This stems from their palette having clear primary and secondary values, which Spark's palette does not however.

Still, I think it would be valuable for Spark to adopt those variant values. Outlined is the mental image I have of that Button styling, whereas secondary doesn't inspire any mental intuition. Likewise for the others.

Adopting Mui's values would also simplify our implementation greatly, as we customize the existing interface and avoid exporting a custom interface.

**Comment by ssbittle** [comment]
@WilliamKelley I'm on board!

**Comment by WilliamKelley** [comment]
Changes have been updated in #158 except for loading spec, but that can be tracked in an isolated issue #164 .
