### ISSUE TITLE
Simplify Figma JS/CSS Color names

### ISSUE THREAD

**Issue by WilliamKelley** [prenda-school/prenda-spark#103]
Currently, the names of our color values are unnecessarily long.

@ssbittle Are the "JS" and "CSS" names of spark's palette listed in "Spark Design System - Base, Colors" important to designers? If not, I'd like to simplify them for our implementation purposes.

**Comment by ssbittle** [comment]
Not important. We can change them to be more simple. No problem.

**Comment by WilliamKelley** [comment]
Great, thank you. I'll make a PR to get feedback from other devs on my new names, then I'll go ahead change the Figma page when it's finalized.

**Comment by WilliamKelley** [comment]
@ssbittle Could you grant me edit access to the "Base" figma doc temporarily so I can replace those names

**Comment by ssbittle** [comment]
Access updated.

**Comment by WilliamKelley** [comment]
Done.

@ssbittle We also have JS values for these rows. Some of which are not reflected in the panels to the right, but are usually the values referenced in designs. Is it acceptable to add on to them as well?

![image](https://user-images.githubusercontent.com/25781782/124007910-d9b2b480-d9a9-11eb-90c0-d34c34abe520.png)

ex: 

"#0A3872" as Label - Medium

to

"*Hex*: #0A4872
*JS*: palette.brand.blue" in Source Code Pro font

or if creating another panel is more appropriate

**Comment by ssbittle** [comment]
@WilliamKelley That makes perfect sense. And I'm personally cool with that change.

**Comment by WilliamKelley** [comment]
@ssbittle Didn't have enough space for the prefixes, but I added them in the best way i could think of. The issue will close once we get our code in line with the new names.

**Comment by ssbittle** [comment]
@WilliamKelley Thanks for doing this.
