### ISSUE TITLE
Select

### ISSUE THREAD

**Issue by WilliamKelley** [prenda-school/prenda-spark#123]
# ✅ Design Done
Variations: Default
Types: Default
Sizes: One
States: default, active , success, error, disabled, filled

### Design reference:
[Figma file - Select](https://www.figma.com/file/y6Ca8BdJtQEd3Of1saRieF/Spark-Design-System-Web?node-id=949%3A17)

**Comment by WilliamKelley** [comment]
### Feedback
@ssbittle 
1. Should the icon be switched to the new "down chevron line"?

### Implementation
Clearly the Mui component is [Select](https://material-ui.com/components/selects/). It will inherit styling from `InputBase` and extend its props. Central to the implementation is also the `Menu` and `MenuItem`'s, however I don't think it should be the responsibility of `Select`'s initial implementation to make sure they're styled all correct -- probably just that `Menu` has the correct offset.

**Comment by ssbittle** [comment]
@WilliamKelley It appears to be pulling from the 'New' library.. but looks more thick in the current design. I'll make sure it is consistent at 1.5.
