### ISSUE TITLE
Switch

### ISSUE THREAD

**Issue by ssbittle** [prenda-school/prenda-spark#147]
### Variations:
**Sizes**: Small, Large

**Design reference:**
[Figma file - Switch](https://www.figma.com/file/y6Ca8BdJtQEd3Of1saRieF/Spark-Design-System-Web?node-id=2129%3A4193)

**Comment by WilliamKelley** [comment]
### Feedback
@ssbittle 
- "Switch" is the standard name for this (see [MDN / w3c standards](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Switch_role))
- Anatomy: 1 should be "track", 2 should be "thumb"
- Very nice to see the Pseudo states prefixed by regular states (e.g. `ON-DEFAULT` v. `OFF-DEFAULT`). Other stories could benefit from the pseudo-states (hover, focus, active) being additions to the base state like this (see Checkbox, Radio, maybe others).
- Missing `ON-FOCUS`, `OFF-FOCUS` and `DISABLED`

### Implementation

Easy Mui parallel, [Switch](https://material-ui.com/api/switch/)

**Comment by WilliamKelley** [comment]
@ssbittle still missing ON-DISABLED and OFF-DISABLED

**Comment by WilliamKelley** [comment]
### Design Feedback

@ssbittle 

- The "Component" and "States" sections have different designs for the default and hover styling of an OFF switch. I assume the correct styling is `medium grey` for default off and `dark grey` for hover off?
- The switch thumb uses an old box shadow preset of "Elevation 03". This doesn't exist in the Foundations spec anymore, and "E300" is not a direct replacement.
