### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by ssbittle** [prenda-school/prenda-spark#148]
### Variations:
**Sizes**: One

**Design reference:**
[Figma file - Tabs](https://www.figma.com/file/y6Ca8BdJtQEd3Of1saRieF/Spark-Design-System-Web?node-id=949%3A1)

**Comment by WilliamKelley** [comment]
### Feedback
@ssbittle 
- Missing `FOCUS` pseudo-state
- `HOVER` pseudo-state doesn't have any styling differences, it probably should?
- Missing 'SELECTED` state and it's pseudo state
  - Maybe you meant this by `ACTIVE`, but know that [`:active` is a pseudo-state](https://developer.mozilla.org/en-US/docs/Web/CSS/:active) that applies on click / press, so selected should be the term used instead.

### Implementation
Clear Mui parallel, [Tabs](https://material-ui.com/components/tabs). We should also suggest standard use of the [experimental API](https://material-ui.com/components/tabs/#experimental-api) pattern with `TabContext` for a11y reasons.
