### ISSUE TITLE
Popover

### ISSUE THREAD

**Issue by ssbittle** [prenda-school/prenda-spark#152]
### Variations:
**Types**: Dark, Light

**Design reference:**
[Figma file - Popover](https://www.figma.com/file/y6Ca8BdJtQEd3Of1saRieF/Spark-Design-System-Web?node-id=1012%3A32)

**Comment by WilliamKelley** [comment]
### Feedback
@ssbittle 
Similar to Tooltip (#154) does Spark want to prescribe a Transition for this?

### Implementation
Clear Mui parallel, [Popover](https://material-ui.com/components/popover).

We'll want to look into this [popup-state 3rd party helper](https://next.material-ui.com/components/popover/#popupstate-helper) that could simplify use cases of this component. Maybe a story with and without.

The component doesn't have color by default, so we should export a wrapped version that will apply utility classes for that. But stick to all styles defined in overrides.

**Comment by ssbittle** [comment]
@WilliamKelley I see these as large tooltips, and would expect that act the same as well.

**Comment by WilliamKelley** [comment]
> @WilliamKelley I see these as large tooltips, and would expect that act the same as well.

That's a good point, it would take on the same implementation as a Tooltip but with just a different styling. 

To that end, should this just be under a variant of the Tooltip design then?

Or at least it should take on a different name than Popover, because in implementation that's just a term for the underlying behavior that powers a lot of components, e.g. Tooltip, Dialog (Modal), etc.

**Comment by ssbittle** [comment]
Name Suggestion: In-line Dialog?

**Comment by WilliamKelley** [comment]
> Name Suggestion: In-line Dialog?

Mmm i think a dialog implies it asks some sort of action or interruptive or blocking content.

After looking around, how about Balloon?

**Comment by ssbittle** [comment]
Not against that. Where did you come across that convention?

**Comment by WilliamKelley** [comment]
No place in particular, but things like [balloon.css](https://kazzkiq.github.io/balloon.css/), the title of this [ADG article](https://www.accessibility-developer-guide.com/examples/widgets/tooltips/).

Was looking for something "bigger" and "richer" than a tooltip, but "smaller" and "lighter" than a dialog. And that wasn't just a universal behavior description like "popover".

**Comment by ssbittle** [comment]
Cool cool! I kind of like the idea of combining the two and putting this under "Tooltip" but as a robust variant. Because essentially they are the same.

I can work on the Figma and then update the issue here.

**Comment by WilliamKelley** [comment]
Sounds good to me!

**Comment by ssbittle** [comment]
@WilliamKelley Design updates to [Tooltip](https://www.figma.com/file/y6Ca8BdJtQEd3Of1saRieF/Spark-Design-System-Web?node-id=1004%3A0)

Simplified.

**Comment by WilliamKelley** [comment]
Moved to #154
