### ISSUE TITLE
Re-export everything?

### ISSUE THREAD

**Issue by WilliamKelley** [prenda-school/prenda-spark#167]
As everything sits currently, consumers have to remember which components they import from spark or material-ui.
- from spark: if our implementation requires a custom wrapper
- from material-ui: if our implementation is fully contained in theme props/overrides.

Additionally we don't have any form of docs to say which each component is. While convenient for us, I think it's ultimately a detriment to consumers.

I propose we re-export _all_ components from Material-UI that we implement stylings for.

**Comment by seigler** [comment]
How does re-exporting affect bundle size and tree-shaking (or fake tree-shaking like in Prenda World)?

**Comment by WilliamKelley** [comment]
> 
> 
> How does re-exporting affect bundle size and tree-shaking (or fake tree-shaking like in Prenda World)?

It wouldn't change the current story. But note the current story probably doesn't live up to your expectations: Spark re-exports from it's _peer-dependency_ Mui. The_ build process outputs one tree-shakable file. Not fake-tree-shakable)

Note that this _was_ the same story for the icons package, until the custom build process.

**Comment by seigler** [comment]
Webpack supports tree-shaking star exports since version 5, so let's go for it.

**Comment by WilliamKelley** [comment]
Cool, was working on it but got very side-tracked. A complete PR would 
- re-export the component for every override we define. 
- change all component uses in stories / tests from material-ui to spark
- add basic existence tests to verify re-exported components exist and render

Right?

**Comment by seigler** [comment]
> re-export the component for every override we define.

Is this necessary? Local exports take precedence over star exports, so we ought to be able to `export * from @material-ui/core` and then export all the things we currently do, like `Typography`.

**Comment by WilliamKelley** [comment]
> Local exports take precedence over star exports, so we ought to be able to `export * from @material-ui/core` and then export all the things we currently do, like `Typography`.

i did not know this was the case! i'll pursue that
