### ISSUE TITLE
Build issue (v0.9)

### ISSUE THREAD

**Issue by shadoath** [prenda-school/prenda-spark#178]
Ran into an issue, when running `meteor run`
```
W20210802-18:20:20.809(-4)? (STDERR) /Users/sbolton/.meteor/packages/meteor-tool/.2.3.2.6kaeg3.h9j24++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20210802-18:20:20.902(-4)? (STDERR) 						throw(ex);
W20210802-18:20:20.902(-4)? (STDERR) 						^
W20210802-18:20:20.902(-4)? (STDERR)
W20210802-18:20:20.903(-4)? (STDERR) TypeError: Cannot set property IconButton of #<Object> which has only a getter
W20210802-18:20:20.903(-4)? (STDERR)     at /Users/sbolton/code/prendaverse/prendaworld/node_modules/@prenda/spark/spark.umd.js:3341:24
W20210802-18:20:20.903(-4)? (STDERR)     at /Users/sbolton/code/prendaverse/prendaworld/node_modules/@prenda/spark/spark.umd.js:2:68
W20210802-18:20:20.903(-4)? (STDERR)     at Object.<anonymous> (/Users/sbolton/code/prendaverse/prendaworld/node_modules/@prenda/spark/spark.umd.js:5:2)
W20210802-18:20:20.903(-4)? (STDERR)     at Module._compile (internal/modules/cjs/loader.js:1085:14)
W20210802-18:20:20.904(-4)? (STDERR)     at Module.Mp._compile (/Users/sbolton/code/prendaverse/prendaworld/.meteor/local/build/programs/server/runtime.js:99:23)
W20210802-18:20:20.904(-4)? (STDERR)     at Object.Module._extensions..js (/Users/sbolton/code/prendaverse/prendaworld/.meteor/local/build/programs/server/runtime.js:131:23)
W20210802-18:20:20.904(-4)? (STDERR)     at Module.load (internal/modules/cjs/loader.js:950:32)
W20210802-18:20:20.904(-4)? (STDERR)     at Module.Mp.load (/Users/sbolton/code/prendaverse/prendaworld/.meteor/local/build/programs/server/runtime.js:46:33)
W20210802-18:20:20.904(-4)? (STDERR)     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
W20210802-18:20:20.904(-4)? (STDERR)     at Module.require (internal/modules/cjs/loader.js:974:19)
W20210802-18:20:20.904(-4)? (STDERR)     at require (internal/modules/cjs/helpers.js:92:18)
W20210802-18:20:20.905(-4)? (STDERR)     at npmRequire (/Users/sbolton/code/prendaverse/prendaworld/.meteor/local/build/programs/server/npm-require.js:133:12)
W20210802-18:20:20.905(-4)? (STDERR)     at Module.useNode (packages/modules-runtime.js:664:18)
W20210802-18:20:20.905(-4)? (STDERR)     at module (/Users/sbolton/code/prendaverse/prendaworld/.meteor/local/build/programs/server/packages/modules.js:1644:8)
W20210802-18:20:20.905(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20210802-18:20:20.905(-4)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
```
Followed that with a `meteor npm i`:
```
npm WARN @prenda/spark@0.9.0 requires a peer of @material-ui/lab@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-loader@8.2.2 requires a peer of webpack@>=2 but none is installed. You must install peer dependencies yourself.
npm WARN css-loader@5.1.1 requires a peer of webpack@^4.27.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-subscriptions@1.1.0 requires a peer of graphql@^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0 || ^14.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN jscodeshift-add-imports@1.0.10 requires a peer of jscodeshift@^0.7.0 || ^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN jscodeshift-find-imports@2.0.4 requires a peer of jscodeshift@^0.7.0 || ^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN less-loader@7.3.0 requires a peer of webpack@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN meteor-jest-stubs@2.1.0 requires a peer of jest-cli@23.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN ts-jest@25.5.1 requires a peer of jest@>=25 <26 but none is installed. You must install peer dependencies yourself.
npm WARN ts-jest@25.5.1 requires a peer of typescript@>=3.4 <4.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-rangeslider@2.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-tag-input@6.5.2 requires a peer of react-dnd@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-tag-input@6.5.2 requires a peer of react-dnd-html5-backend@^3.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN style-loader@2.0.0 requires a peer of webpack@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN The package @types/styled-components is included as both a dev and production dependency.
```

`meteor npm -v` => `6.14.12`
`node -v`  => `v12.22.1`

Will provide more input tomorrow.

Here is the [Cypress test](https://github.com/prenda-school/prendaworld/runs/3225420445) showing the error.

**Comment by WilliamKelley** [comment]
Would be helpful to know the command you ran -- copy-paste the command from invocation to output finish.

I'm guessing the first log is from building your project, and the second is from `npm update`.

The first log is cryptic, but I found this: https://github.com/evanw/esbuild/issues/587 . Suggesting that the issue is with
```
export * from '@material-ui/core'; // exports IconButton
export * from './IconButton'; // also exports IconButton
```
Quoting from the link, "Each export is exposed as a writable property even though you can't write to it. [in the context of esbuild]" So essentially that the initial re-export (from Mui) cannot be overridden (with Spark's) with some build tools? 

The second log seems unrelated to the error, mostly `npm` warning you that you don't have a lot of necessary `peerDependencies` installed. But, you should pay attention to and fix Spark's while you're there:
```
npm WARN @prenda/spark@0.9.0 requires a peer of @material-ui/lab@^4.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by WilliamKelley** [comment]
@seigler Any ideas/knowledge on the error source and possible relation to the wildcard override?

**Comment by seigler** [comment]
I updated Spark on a local branch of Prenda World and didn't experience that TypeError, but I don't know how my environment is difference from Skylar's.
I think we could adopt the same solution as they did in the esbuild issue you linked, since we are forced to use Meteor's bundler, and it has the same issue as esbuild.

**Comment by WilliamKelley** [comment]
@seigler Could you run the cypress suite and see if it passes? 

@shadoath Are you able to reproduce the error on your local? If so, can you push a branch up with the state and lmk so I can test.

And for good measure, found another source on how to handle the wildcard issue, if that's really what this is. https://github.com/benwiley4000/wildcard-export-override-example

**Comment by seigler** [comment]
I actually am getting the error now, after including some new work from develop.

**Comment by WilliamKelley** [comment]
From discussion / experimenting with Skylar/Scott, looks like neither article details an actually workable solution for us.

The only thing we can work out is manually re-export everything don't override from Mui. e.g.
```tsx
export {
  allTheirUtilities,
  ComponentWeDontOverride
} from '@material-ui';
export { Our Component } from './OurComponent';
```

Which is the worst outcome, but our only path forward if we want to guarantee this functionality for consumers.

**Comment by WilliamKelley** [comment]
My comment on #179, which i probably should have posted here first

> The narrative that this creates for consumers doesn't sit well with me: "Consumers have to know which components Spark exports a _custom wrapper_ for." We can't re-export everything, but can we find a suitable middle ground?
>
>My proposal: 
>- Re-export every component that we support. 
>    - Ideally in the component's respective file. Then in the index like our custom wrappers.
>- Re-export common utilities, namely `withStyles`, `styled`, `makeStyles`. Any others?
>
>The benefits:
>- Acceptable narrative (in my opinion): "Consumers have to know which components Spark supports."
>- Consumers that don't reach for non-supported components or advanced utilities won't have to import anything from '@material-ui/core' -- thus we've abstracted MUI for naive/basic applications.
>    - Our storybook should fall under this category.
>- Our added maintenance cost at most 2 statement more, per-component, plus the limited utilities.
>    - We can be confident that the most common utilities won't break.
>
>Thoughts?
