### ISSUE TITLE
Dropdown event handlers

### ISSUE THREAD

**Issue by seigler** [prenda-school/prenda-spark#185]
The Dropdown custom component uses its own internal event handling to manage state (open, closed). It might be valuable to emphasize this in the eventual documentation for this component, since the button and menu still accept onClick and onClose props, respectively.
Alternatively, those props could be removed from `SparkDropdownButton` and `SparkDropdownMenu` so overriding them is not possible.

**Comment by WilliamKelley** [comment]
I think Spark should consumers to pass an independent onClick handler while still ensuring the dropdown open will fire -- they wouldn't be using the dropdown components otherwise. For example
```
onClick={(event) => {
  passedOnClick(event);
  internalOnClick(event);
}}
```
