### ISSUE TITLE
Design: Inconsistent Heading line-height

### ISSUE THREAD

**Issue by WilliamKelley** [prenda-school/prenda-spark#190]
The line-height actual value vs written value for _all headings_ is inconsistent in the Typography Figma file./I'm assuming the actual values are right and the written values are wrong.

Ex: XLarge writes 40px but has 48px
![image](https://user-images.githubusercontent.com/25781782/129418063-746b26a6-bf51-421a-bd73-cf32fabadf34.png)

Additionally, since the Typography has been split off to its own file, can it be removed from the Foundations file?

#### Possible assignee's

@ssbittle @alecdanz

**Comment by WilliamKelley** [comment]
I actually do notice a difference between the Typography's. One calls a group "Small Caps", the other calls it "uppercase"

**Comment by ssbittle** [comment]
@WilliamKelley Addressing this. Will remove documentation from Foundations file, and update the new source of truth in "Typography" file.
