### ISSUE TITLE
Line-height mismatch in Typography Labels

### ISSUE THREAD

**Issue by WilliamKelley** [prenda-school/prenda-spark#202]
Some Typography labels, `Medium`, `Medium - Strong`, `Small`, `Small - Strong`, state one line height but implement another. And the `Small` variant has a mismatch between its regular and strong variant, where the strong variant has a different line-height.

This discrepancy is affecting the auto-layout of other components using those variants, like `Button` of `size="small"`.

cc: @ssbittle

**Comment by ssbittle** [comment]
Addressed and updated.

**Comment by WilliamKelley** [comment]
@ssbittle Thanks! The Typography file is consistent for me now. But the Button, size small, copmonent is still using the old values, do the changes need to be accepted for that? Or is it a custom difference then.

**Comment by ssbittle** [comment]
> @ssbittle Thanks! The Typography file is consistent for me now. But the Button component, size small, is still using the old values, do the changes need to be accepted for that? Or is it a custom difference then.

Will need to update those components to reflect changes.

**Comment by WilliamKelley** [comment]
Bump: small button still using old styles

**Comment by ssbittle** [comment]
Update complete.
