### ISSUE TITLE
Input component updates

### ISSUE THREAD

**Issue by alecdanz** [prenda-school/prenda-spark#224]
Updates have been made to the input component. A larger color change will be coming soon (we are evaluating accessibility as it relates to different colors in the design system). 

The states remain the same for the most part. The largest change is that the default for form fields will also have a white background. 

https://www.figma.com/file/y6Ca8BdJtQEd3Of1saRieF/Spark-Web-components?node-id=207%3A0

**Comment by WilliamKelley** [comment]
@alecdanz Seems like "Select field" should also change as well?
