### ISSUE TITLE
Determine if TSDX should remain in code base

### ISSUE THREAD

**Issue by haase1020** [prenda-school/prenda-spark#36]
TSDX is causing issues with building Storybook https://github.com/prenda-school/prenda-spark/pull/24. TSDX (per its website) is "a zero-config CLI that helps you develop, test, and publish modern TypeScript packages", but after having faced these issues, it might be helpful to reconsider if this package is worth keeping in Spark or if other alternatives are available.

**Comment by seigler** [comment]
Is [nx](https://nx.dev/) a viable alternative? I would love to pair sometime to explore it; an old coworker was showing adding a component to his Storybook library and it looked like an amazing dev experience.

**Comment by haase1020** [comment]
I would love to pair on that together! Do you want to work on this task together?

**Comment by seigler** [comment]
NX info:
supports react, storybook, publishing libraries to npm
https://nx.dev/latest/react/storybook/overview
https://nx.dev/latest/angular/structure/buildable-and-publishable-libraries

**Comment by WilliamKelley** [comment]
Migrated from slack convo:

https://nx.dev/latest/angular/migration/overview

**Comment by WilliamKelley** [comment]
Linking #37 as a motivator for moving to NX for its multi-project support. A separate icon library package would be ideal for that.

**Comment by WilliamKelley** [comment]
Closed by #39
