### ISSUE TITLE
Checkbox Control defaulting to MUI secondary color

### ISSUE THREAD

**Issue by awburgard** [prenda-school/prenda-spark#40]
When using the Spark checkbox:

Code example:

```
<Checkbox
  checked={microschoolProfile.grades.indexOf(grade) > -1}
  control={<Checkbox />}
  label={grade}
 />
```

The component works fine but if a the checkbox is unchecked, it defaults to the default MUI checkbox, specifically the secondary default color. 

![Screen Shot 2021-05-18 at 12 52 23 PM](https://user-images.githubusercontent.com/47367507/118700101-e7382480-b7d7-11eb-89f0-29447ac5f626.png)

**Comment by WilliamKelley** [comment]
The props signature of Checkbox needs to omit 'control'.

But otherwise, a correct pattern would be to not set the control. The internal implemenation of Spark's Checkbox already does this, and the component is really a FormControlLabel. Maybe that's a poor pattern.

```
<Checkbox checked={...} label={...} />
```

**Comment by awburgard** [comment]
@WilliamKelley it does not. I'm still getting the same behavior when I remove control.

**Comment by awburgard** [comment]
Looks like the color is being inherited from the base mui icon button

![Screen Shot 2021-05-18 at 2 04 06 PM](https://user-images.githubusercontent.com/47367507/118710605-23718200-b7e4-11eb-96bf-159a3abf8880.png)

**Comment by WilliamKelley** [comment]
### The fix 
1. Add a story for CheckboxGroup that mimics [this MUI demo](https://material-ui.com/components/checkboxes/#checkboxes-with-formgroup). 
2. Fix styling issues
    - The "right" styling isn't formally defined for a CheckboxGroup, so this should just be best judgement. (I'll file a separate issue for a more general refactor and addition of other styled components to aid the whole solution to this)
