### ISSUE TITLE
Missing design for RadioGroup & CheckboxGroup

### ISSUE THREAD

**Issue by WilliamKelley** [prenda-school/prenda-spark#42]
The Spark Web Figma resource is lacking specs on how multiple Checkbox inputs should be used together, referred to as a FormGroup (and likewise for Radio). Even though the current design displays checkboxes/radios in sequence, it just seems to be as individual states/pseudo-states, not as a group. Ideally the spec would have
- Label for the group (usually above)
- Helper Text for the group (usually below)
- Error styling
- Horizontal & Vertical orientation with desired spacing between Checkbox elements in each layout

For reference, [this MUI demo](https://material-ui.com/components/checkboxes/#checkboxes-with-formgroup) displays the default Material Design theme spec for multiple Checkboxes in a FormGroup, and [likewise here](https://material-ui.com/components/checkboxes/#checkboxes-with-formgroup) for Radios in a custom FormGroup (RadioGroup)

**Comment by ssbittle** [comment]
**Design Updated** 

**Files**:
[Checkboxes](https://www.figma.com/file/y6Ca8BdJtQEd3Of1saRieF/Spark-Design-System-Web?node-id=1056%3A1286)
[Radio button](https://www.figma.com/file/y6Ca8BdJtQEd3Of1saRieF/Spark-Design-System-Web?node-id=1056%3A1285)
