### ISSUE TITLE
Extract Menu design from Dropdown and Select

### ISSUE THREAD

**Issue by WilliamKelley** [prenda-school/prenda-spark#46]
Currently the [Dropdown design file](https://www.figma.com/file/y6Ca8BdJtQEd3Of1saRieF/?node-id=668%3A175) contains the design for a Menu and MenuItem. I think that Menu should be extracted into it's own file. Notably because we can maintain it as a single dev item that is used in the Dropdown and [Select Field design](https://www.figma.com/file/y6Ca8BdJtQEd3Of1saRieF/?node-id=949%3A17). 

Then, the Dropdown file just specifies acceptable composition patterns of a components that can trigger the Menu to appear (e.g. a Button, Avatar), the spacing between elements (e.g. between the Button and Menu), and the vertical/horizontal offset and alignment options (e.g. aligned with right edge of anchoring element, offset to the bottom, or vice versa, etc.). This is genuinely the standard definition of what a "Dropdown" should specify. A "Menu" is the box and items that are currently designed embedded in the Dropdown design file.

Another motivation for this is that a "Menu with checkbox" doesn't make sense for a menu that appears as part of a "Dropdown", however it does for a "Select Field" since it can be a nice display for a multi-select form element.

**Comment by ssbittle** [comment]
**Design updated.**

[Dropdown page](https://www.figma.com/file/y6Ca8BdJtQEd3Of1saRieF/Spark-Design-System-Web?node-id=1674%3A0)

[Menu page](https://www.figma.com/file/y6Ca8BdJtQEd3Of1saRieF/Spark-Design-System-Web?node-id=1674%3A0)
