### ISSUE TITLE
Avatars

### ISSUE THREAD

**Issue by ssbittle** [prenda-school/prenda-spark#52]
### Variations:
**Types**: `Image`, `Icon`, `Image`
**Sizes**: Scalable

**Design reference:**
[Figma file - Avatar](https://www.figma.com/file/y6Ca8BdJtQEd3Of1saRieF/Spark-Design-System-Web?node-id=949%3A465)

**Comment by ssbittle** [comment]
@WilliamKelley Yes. Will update.

**Comment by WilliamKelley** [comment]
@ssbittle Can you send me the original image files for the Spark Design System - Base, Media page? I tried exporting from Figma and they're blurry.
![Guide 1](https://user-images.githubusercontent.com/25781782/125987507-dac4257c-90c5-4a82-b091-259828b2c49b.png)

**Comment by ssbittle** [comment]
[spark.media-avatars.zip](https://github.com/prenda-school/prenda-spark/files/6832691/spark.media-avatars.zip)

@WilliamKelley

**Comment by WilliamKelley** [comment]
### Design Feedback

@ssbittle It seems that "large" is using a standard typography "Heading/Large" but the others do not, and use impossible font size values: `19.6`, `11.2`, `8.4`. Can you resolve that please?

**Comment by WilliamKelley** [comment]
@ssbittle Can you also specify the icon dimensions for each size as well please?

**Comment by WilliamKelley** [comment]
@ssbittle It seems that the NavBar example uses a non-standard size, 40x40, which is in between medium and small. Is that intentional?

**Comment by ssbittle** [comment]
@WilliamKelley No. That has been corrected to reflect size Medium.
