### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by ssbittle** [prenda-school/prenda-spark#53]
### Variations:
**Types**: `Remove`, `Basic`
**Sizes**: One

**Design reference:**
[Figma file - Tag](https://www.figma.com/file/y6Ca8BdJtQEd3Of1saRieF/Spark-Design-System-Web?node-id=949%3A467)

**Comment by WilliamKelley** [comment]
### Feedback
None

### Implementation
Mui parallel: [Chip](https://material-ui.com/components/chips/#chip)

Custom variants: "bold", "subtle" (default)
    - inherit from existing "default" variant
    - ignore existing "outlined" variant
Custom colors: our tertiary colors "red", "orange", "yellow", "green", "blue", "purple"
    - existing "default" can be the white/grey design
    - ignore existing "primary", "secondary" colors

We'll have to supply our custom delete icon by default, validate the styling, create separate stories, etc. the usual.

Given the custom name, variants and colors, this should be a custom wrapper before the v5 migration.

**Comment by WilliamKelley** [comment]
#### Design Feedback

I see this component's name has been changed to "Badge". I believe its name should stay as "Tag". Because, Badge is already well-identified as the notification or numeric dot somewhere around an icon. 

See Mui's component: https://material-ui.com/components/badges/

On every design system I could find, Badge is described like "a visual indicator of numerical characterisitics of an object, and they are generally actionless". Both things are not true about Spark's badge/tag

cc: @ssbittle

**Comment by ssbittle** [comment]
@WilliamKelley I'm for that. Will update.

**Comment by WilliamKelley** [comment]
#### Design Feedback

The subtle, yellow tag has "Palette/Orange 5" text color, whereas I would've expected it to have "Palette/Yellow 5". Is this intentional?

cc: @ssbittle

**Comment by ssbittle** [comment]
@WilliamKelley Fixed.

**Comment by WilliamKelley** [comment]
#### Design Feedback

Can you enumerate the "X" icon hover states for each color and variant combination? I can guess that the pattern of the one "Behavior" example means that for `variant="subtle"`, the icon color should change to `white` and the background color to `red/orange/.../purple[5]`. But when `variant="bold"`, should the color change to `red/.../purple[5]` and background color to `white`?

cc: @ssbittle

**Comment by ssbittle** [comment]
I will mock up examples so this is more clear.

**Comment by ssbittle** [comment]
Unsure about your comment about dashed border. Where are you seeing this?

**Comment by WilliamKelley** [comment]
> Unsure about your comment about dashed border. Where are you seeing this?

Seems to be gone now, i think it was some Figma selection styling, not actual styling, sorry about that
