### ISSUE TITLE
Only use inside borders

### ISSUE THREAD

**Issue by WilliamKelley** [prenda-school/prenda-spark#62]
It would be much easier to match designs if only 'inside' borders were used. 

Ensuring an elements width/height in respect to its content and border is usually helped by the [box-sizing](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing) property where the best standard is `border-box`. That value ensures the width/height is the sum of border and content, matching the behavior of an 'inside' border.

Affected components afaik: Button

**Comment by ssbittle** [comment]
Design updated.
