### ISSUE TITLE
Version repository as a whole

### ISSUE THREAD

**Issue by WilliamKelley** [prenda-school/prenda-spark#65]
When i set up the semver plugin, I set it to version nx projects separately. My thought was when we have `@prenda/spark-icons` ([Issue](#37)) in addition to `@prenda/spark` right now, they could be versioned independently. Not wholly bad, but it has the downside of segmenting our repository's [Releases](https://github.com/prenda-school/prenda-spark/releases) and changelog to be more cumbersome and project specific. I think it'd be better to just version the repository as a whole.

**Comment by shadoath** [comment]
I'm in agreement to version the repo as a whole.
