### ISSUE TITLE
Separate `@prenda/spark-icons`, revise generation method

### ISSUE THREAD

**Issue by WilliamKelley** [prenda-school/prenda-spark#73]
Given that #68 introduced ~1700 icon files, we need to be very specific and careful about how we're defining and exporting them.

### Problems

- The 1700 files take up ~2.41 MB of raw space, and even more on a user's disk depending on their disk file format (see below).
  - This enormous file count and overall size can bring bundlers to a literal crawl if the library isn't correctly tree-shakable / or icons aren't otherwise directly importable -- I have a feeling that with all the problems consumers have had, our library currently falls under this category.
- Current directory layout prevents consumer from specifying the same [import transform plugin rule](https://material-ui.com/guides/minimizing-bundle-size/#option-2) that MUI advises.
- Icon svg files are not optimized and contain unneeded accessory info.

![image](https://user-images.githubusercontent.com/25781782/122787046-f0a72780-d282-11eb-91e2-8324148507be.png)

### Solution

- Create new package `@prenda/spark-icons` -- overall this will mirror [`@material-ui/icons`](https://github.com/mui-org/material-ui/tree/latest/packages/material-ui-icons)
- Locate all icons in top-level of `src/`
  - Mimic [MUI's naming scheme](https://material-ui.com/components/icons/#usage)
```bash
src
├── Activity.tsx # Line variant, default (no suffix)
├── ActivityFilled.tsx # Filled variant
├── ActivityDuotone.tsx # Duotone variant
```
- After bulk export from Figma, create a script with [SVGO](https://github.com/svg/svgo) that's similar to [MUI's script](https://github.com/mui-org/material-ui/blob/latest/packages/material-ui-icons/builder.js) to rename and optimize the `path` tags of the SVG. 
  - The optimized output ideally is: 
    - 1 path tag per icon (duotone maybe requires 2)
    - one `d` attribute per tag (`fillRule`, `clipRule` might be unavoidable by just using SVGO though, that'd be fine).
    - completely get rid of `svg` tag definition, the `SvgIcon` component takes care of this for us.
  - File mimics [MUI's layout](https://github.com/mui-org/material-ui/blob/latest/packages/material-ui-icons/src/AcUnit.js)
    - Copy their [internal `createSvgIcon` util](https://github.com/mui-org/material-ui/blob/42954448866f204b0cf7e35127d5d0af9c24d6fb/packages/material-ui/src/utils/createSvgIcon.js#L7) to our codebase

**Comment by WilliamKelley** [comment]
#### Affectees

@seigler @shadoath

**Comment by WilliamKelley** [comment]
My proposal heavily advocates just copying most of MUI's methods because like always, they've had years of experience in these areas and produce a great working product. This can cut our dev work and additional load significantly.

**Comment by shadoath** [comment]
The idea of `@prenda/spark-icons` makes sense. They are unique enough and simple enough to be manage outside of the main spark components.  We definitely want to work with treeshaking for these.

**Comment by seigler** [comment]
The tool I used to transform the SVG files to typescript React components is [svgr](https://react-svgr.com/). The specific command was:
```bash
npx @svgr/cli --icon --replace-attr-values "#072E44=currentcolor" -d ./ ./
```

SVGR does include an SVGO pass, but maybe there is room for additional optimization.

**Comment by WilliamKelley** [comment]
Okay cool, I saw SVGR as well, that'll be easier than a custom script if we can get what we want out of it.

**Comment by WilliamKelley** [comment]
Chromatic storybook builder is complaining about the file size of using all the icons: 

```bash
ERR! asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
ERR! This can impact web performance.
ERR! Assets: 
ERR!   main.28237df2.iframe.bundle.js (3.48 MiB)
ERR!   vendors~main.8024c826.iframe.bundle.js (2.12 MiB)
ERR! entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
ERR! Entrypoints:
ERR!   main (5.6 MiB)
ERR!       runtime~main.4c84b20b.iframe.bundle.js
ERR!       vendors~main.8024c826.iframe.bundle.js
ERR!       main.28237df2.iframe.bundle.js
ERR! 
```

**Comment by WilliamKelley** [comment]
Examining the NPM Publish action, our e2e app test shows size complaints as well

```bash
Version: webpack 4.42.0
Time: 36904ms
Built at: 07/01/2021 2:22:50 PM
                         Asset       Size        Chunks                    Chunk Names
           0.manager.bundle.js    111 KiB             0  [emitted]         
           1.manager.bundle.js    360 KiB             1  [emitted]  [big]  
           2.manager.bundle.js   66.8 KiB             2  [emitted]         
           3.manager.bundle.js    372 KiB             3  [emitted]  [big]  
           4.manager.bundle.js  649 bytes             4  [emitted]         
           5.manager.bundle.js   15.1 KiB             5  [emitted]         
           6.manager.bundle.js   1.36 KiB             6  [emitted]         
                    index.html   2.38 KiB                [emitted]         
        main.manager.bundle.js   4.91 KiB          main  [emitted]         main
runtime~main.manager.bundle.js   8.95 KiB  runtime~main  [emitted]         runtime~main
vendors~main.manager.bundle.js   4.51 MiB  vendors~main  [emitted]  [big]  vendors~main
Entrypoint main [big] = runtime~main.manager.bundle.js vendors~main.manager.bundle.js main.manager.bundle.js
```

and about a thousand lines of 
```bash
Error from chokidar (/home/runner/work/prenda-spark/prenda-spark/libs/spark): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/runner/work/prenda-spark/prenda-spark/libs/spark'
```

**Comment by WilliamKelley** [comment]
I will be working on this today

**Comment by WilliamKelley** [comment]
Good news on this, I was able to clone the `material-ui` repo, modify Mui's script, and use it against our figma icon exports to produce a desirable output for all of our 3 icon types. I just have to work on the suffix naming and looking for special cases where things like the icon name needs to be substituted (ex: `360Degrees` -> `ThreeSixtyDegrees`, variables can't start with a number).

While Figma has an API, I don't think I will automate the export of the icons yet. That might take a while to get right, and I want this to get out ASAP.

It's straightforward enough to bulk-export them out of Figma using the SVG Export plugin. We'll apply NO optimizations in that plugin (even though it definitely just uses SVGO under the hood), we'll let the script take care of all the things.

**Comment by WilliamKelley** [comment]
Forgot to mention that we should use the script over SVGR mainly because SVGR doesn't allow a custom extraction of just the path elements and change the `svg` tag parent to something like `SvgIcon` or just calling a util like `createSvgIcon`. The custom script can handle that complex of a template.
