### ISSUE TITLE
Use common images in stories

### ISSUE THREAD

**Issue by WilliamKelley** [prenda-school/prenda-spark#81]
Recent PR for an unrelated component triggered a [Chromatic UI change review](https://www.chromatic.com/test?appId=60b7f55f55fbd4004993da4c&id=60da2bb77d42af00390ddc16) because the cat pics website returns a random image every time. 

We should switch to using determinate images, probably just copy-pasting the ones used in the Figma files for cohesion. The cat pictures are also low quality anyways.

#### Affectees

@seigler

**Comment by WilliamKelley** [comment]
@ssbittle Do you know where I can find the image used in one of the [Card Examples in Figma](https://www.figma.com/file/y6Ca8BdJtQEd3Of1saRieF/Spark-Design-System-Web?node-id=665%3A4)? I tried exporting it, but it comes out rounded.

It'd be a creature comfort to have the same assets across Figma and Storybook to use in examples

**Comment by ssbittle** [comment]
@WilliamKelley I updated the default image, and here is the file you can use. 
![Card image](https://user-images.githubusercontent.com/83429562/124643613-e413f900-de56-11eb-919d-5226c4acc09a.jpg)
